### ISSUE TITLE
vum 安装时，eslint报错呀 

### ISSUE THREAD

**Issue by 66eagle** [vum-team/vum#50]
ERROR  Failed to compile with 1 errors                                                 08:51:05

Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/www/vum/node_modules/_eslint@3.19.0@eslint/lib/config.js:162:35)
    at Config.getConfig (/www/vum/node_modules/_eslint@3.19.0@eslint/lib/config.js:260:26)
    at processText (/www/vum/node_modules/_eslint@3.19.0@eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/www/vum/node_modules/_eslint@3.19.0@eslint/lib/cli-engine.js:754:26)
    at lint (/www/vum/node_modules/_eslint-loader@1.9.0@eslint-loader/index.js:218:17)
    at Object.module.exports (/www/vum/node_modules/_eslint-loader@1.9.0@eslint-loader/index.js:213:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
> Listening at http://localhost:8080

报错呀。 这个怎么处理呀。

**Comment by 66eagle** [comment]
现在是 git clone 回来。 再执行安装。 就可以了。 不知道为什么。 有可能是有些隐掉的文件打包不回来的问题。
